---
## Openshift product versions and repos to install from
openshift_enable_service_catalog: false
template_service_broker_install: false
openshift_web_console_install: false

openshift_deployment_type: openshift-enterprise
openshift_release: v3.10
openshift_additional_repos:
- id: ose-repo
  name: rhel-7-server-ose-3.10-rpms
  baseurl: http://192.0.2.253/repos/rhel-7-server-ose-3.10-rpms
  enabled: 1
  gpgcheck: 0

- id: rhel-7-server-rpms-repo
  name: rhel-7-server-rpms
  baseurl: http://192.0.2.253/repos/rhel-7-server-rpms
  enabled: 1
  gpgcheck: 0

- id: rhel-7-server-extras-rpms-repo
  name: rhel-7-server-extras-rpms
  baseurl: http://192.0.2.253/repos/rhel-7-server-extras-rpms
  enabled: 1
  gpgcheck: 0

openshift_disable_check: disk_availability,memory_availability,docker_storage,package_availability,package_version

# Default domain to access the applications running on OpenShift.
openshift_master_default_subdomain: "apps.{{ (openshift_openstack_clusterid|trim == '') | ternary(openshift_openstack_public_dns_domain, openshift_openstack_clusterid + '.' + openshift_openstack_public_dns_domain) }}"

# Domain to access the OpenShift UI and API.
openshift_master_cluster_public_hostname: "console.{{ (openshift_openstack_clusterid|trim == '') | ternary(openshift_openstack_public_dns_domain, openshift_openstack_clusterid + '.' + openshift_openstack_public_dns_domain) }}"

openshift_hosted_router_wait: True
openshift_hosted_registry_wait: True
openshift_disable_check: disk_availability,memory_availability,docker_storage,package_availability,package_version

# other default values
openshift_master_default_subdomain: "apps.{{ openshift_openstack_clusterid }}.{{ openshift_openstack_public_dns_domain }}"
openshift_master_cluster_public_hostname: "console.{{ openshift_openstack_clusterid }}.{{ openshift_openstack_public_dns_domain }}"
osm_default_node_selector: 'region=primary'
openshift_hosted_router_wait: True
openshift_hosted_registry_wait: True
openshift_hostname_check: false
ansible_become: true

# Openstack
## Openstack credentials
openshift_cloudprovider_kind: openstack
openshift_cloudprovider_openstack_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
openshift_cloudprovider_openstack_username: "{{ lookup('env','OS_USERNAME') }}"
openshift_cloudprovider_openstack_password: "{{ lookup('env','OS_PASSWORD') }}"
openshift_cloudprovider_openstack_tenant_name: "{{ lookup('env','OS_PROJECT_NAME') }}"
openshift_cloudprovider_openstack_region: "regionOne"
openshift_cloudprovider_openstack_domain_name: "{{ lookup('env','OS_USER_DOMAIN_NAME') }}"
openshift_cloudprovider_openstack_blockstorage_version: v2



openshift_hostname_check: false
ansible_become: true
