---
- hosts: localhost
  roles:
  - {role: master-create, tags: [ 'create' ]}
- hosts: created_master_nodes 
  remote_user: cloud-user
  become: true
  become_method: sudo
  become_user: root
  roles:
  - {role: master-config, tags: [ 'config' ]}
