---
# tasks file for roles/osp-flavor
 - name: Create OCP  Node Flavor
   os_nova_flavor:
     cloud: "{{ cloud_name }}"
     state: "{{ state }}"
     name: ocp-node-flavor
     ram: "{{ node_mem }}"
     vcpus: "{{ node_cpu }}"
     disk: "{{ node_disk }}"
 - name: Set the Node Flavor as a Virtual Flavor
   shell: |
     source "{{ rc_path }}"
     openstack flavor set ocp-node-flavor --property baremetal=flase

