---
# tasks file for osp-securitygroup
  - name:  Allow ICMP to Infra Node
    os_security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: infra_sg 
      protocol: "{{ proto[2] }}"
      remote_ip_prefix: "{{ ip[0] }}"
  - name: Allow SSH Access to Infra Node from Internal Hosts
    os_security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: infra_sg 
      protocol: "{{ proto[0] }}"
      port_range_min: "{{ ports[9] }}"
      port_range_max: "{{ ports[10] }}"
      remote_group: "{{ item }}"
    with_items:
     - master_sg
     - node_sg
     - bastion_sg
     - infra_sg
  - name: Allow LB access to Router
    os_security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: infra_sg 
      protocol: "{{ proto[0] }}"
      port_range_min: "{{ item }}"
      port_range_max: "{{ item }}"
      remote_group: lb_sg
    with_items:
      - "{{ ports[4] }}"
      - "{{ ports[14] }}"
  - name: Allow OpenShift SDN Communication Between the Nodes
    os_security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: infra_sg 
      protocol: "{{ proto[1] }}"
      port_range_min: "{{ ports[1] }}"
      port_range_max: "{{ ports[1] }}"
      remote_group: "{{ item }}"
    with_items:
      - master_sg
      - node_sg 
  - name: Allow Master to Node Agent Communication
    os_security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: infra_sg
      protocol: "{{ proto[0] }}"
      port_range_min: "{{ ports[6] }}"
      port_range_max: "{{ ports[6] }}"
    remote_group: master_sg
  - name: Allow ElasticSearch Cluster Communication
    os_security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: infra_sg
      protocol: "{{ proto[0] }}"
      port_range_min: "{{ ports[13] }}"
      port_range_max: "{{ ports[13] }}"
      remote_group: infra_sg
  - name: Allow all Egress
    os_security_group_rule:
      cloud: "{{ cloud_name }}"
      security_group: infra_sg
      direction: egress
      protocol: "{{ item }}"
    with_items:
        - "{{ proto[0] }}"
        - "{{ proto[1] }}"
        - "{{ proto[2] }}"
