---
# tasks file for osp-securitygroup
  - name: Create the OCP Security Groups
    os_security_group:
      cloud: "{{ cloud_name }}"
      state: "{{ state }}"
      name: "{{ item }}"
      description: open_ocp_ports
    with_items:
      - bastion_sg
      - master_sg
      - node_sg
      - infra_sg
      - lb_sg
